### 位置编码

In [5]:
import torch

x=torch.rand(4,8)
x

tensor([[0.3672, 0.2487, 0.2339, 0.9048, 0.4301, 0.8073, 0.7622, 0.9083],
        [0.6227, 0.4660, 0.3165, 0.3945, 0.7072, 0.8864, 0.4966, 0.4066],
        [0.3141, 0.1676, 0.2378, 0.9156, 0.4928, 0.5503, 0.5766, 0.3559],
        [0.0524, 0.9829, 0.6516, 0.4320, 0.8758, 0.9815, 0.7877, 0.0507]])

In [ ]:
seq_len=4
d_model=8

In [ ]:
pe=torch.zeros(seq_len,d_model)
pe

In [ ]:
pos=torch.arange(0,seq_len)
pos

In [ ]:
pe[:,0]=torch.sin(pos/10000**(2*0/d_model))
pe[:,2]=torch.sin(pos/10000**(2*1/d_model))
pe[:,4]=torch.sin(pos/10000**(2*2/d_model))
pe[:,6]=torch.sin(pos/10000**(2*3/d_model))
pe

In [ ]:
pe[:,1]=torch.cos(pos/10000**(2*0/d_model))
pe[:,3]=torch.cos(pos/10000**(2*1/d_model))
pe[:,5]=torch.cos(pos/10000**(2*2/d_model))
pe[:,7]=torch.cos(pos/10000**(2*3/d_model))
pe

In [3]:
import math
import torch

seq_len=4
d_model=8
pe=torch.zeros(seq_len,d_model)
position=torch.arange(0,seq_len,dtype=torch.float).unsqueeze(1)
div_term=torch.exp(torch.arange(0,d_model,2).float()*(-math.log(10000.0)/d_model))
pe[:,0::2]=torch.sin(position*div_term)
pe[:,1::2]=torch.cos(position*div_term)
pe

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
          9.9995e-01,  1.0000e-03,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
          9.9980e-01,  2.0000e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
          9.9955e-01,  3.0000e-03,  1.0000e+00]])

In [6]:
x*pe

tensor([[ 0.0000e+00,  2.4873e-01,  0.0000e+00,  9.0477e-01,  0.0000e+00,
          8.0732e-01,  0.0000e+00,  9.0826e-01],
        [ 5.2395e-01,  2.5176e-01,  3.1598e-02,  3.9250e-01,  7.0719e-03,
          8.8631e-01,  4.9656e-04,  4.0657e-01],
        [ 2.8558e-01, -6.9746e-02,  4.7248e-02,  8.9737e-01,  9.8557e-03,
          5.5022e-01,  1.1531e-03,  3.5590e-01],
        [ 7.3894e-03, -9.7307e-01,  1.9257e-01,  4.1274e-01,  2.6269e-02,
          9.8107e-01,  2.3632e-03,  5.0744e-02]])